project:
  type: website
  output-dir: docs
website:
  title: psbss2024 | 0.0.5
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: course_notes.qmd
      text: Course Notes
    - href: exercises.qmd
      text: Exercises
    - href: solutions.qmd
      text: Solutions
    - href: add_info.qmd
      text: Additional Information
    - href: News.html
      text: News
    - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
