---
title: "Additional Information"
---

This website provides links to 

## Slides

```{r}
#| label: table-slides
#| echo: false
#| results: asis
s_sl_url <- "https://charlotte-ngs.github.io/psbss2024/slides/"
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3),
                         Date = c("2024-04-24",
                                  "2024-04-24",
                                  "2024-05-15"),
                         Topic = c(
                           paste0("[Introduction](", 
                                  s_sl_url, 
                                  "l01_psb_intro.pdf)",
                                  collapse = ""),
                           paste0("[Genetic Evaluation](",
                                  s_sl_url,
                                  "l02_psb_gen_eval.pdf)",
                                  collapse = ""),
                           paste0("[Aggregate Genotype](",
                                  s_sl_url,
                                  "l03_psb_pbv.pdf)",
                                  collapse = "")
                         ))
knitr::kable(tbl_sl)
```


## Data

```{r}
#| label: table-data
#| echo: false
#| results: asis
s_data_url <- "https://charlotte-ngs.github.io/psbss2024/data/"
tbl_data <- tibble::tibble(Nr = c(1),
                           Date = c("2024-04-24"),
                           Topic = c(
                             paste0("[Model Selection](",
                                    s_data_url,
                                    "psb_rand_pred.csv)",
                                    collapse = "")
                           ))
knitr::kable(tbl_data)
```



## Overhead

```{r}
#| label: table-ohp
#| echo: false
#| results: asis
s_ohp_url <- "https://charlotte-ngs.github.io/psbss2024/ohp/"
tbl_ohp <- tibble::tibble(Nr = c(1),
                          Date = c("2024-04-24"),
                          Topic = c(
                            paste0("[Introduction](",
                                   s_ohp_url,
                                   "20240424_ohp_l01.pdf)",
                                   collapse = "")
                          ))
knitr::kable(tbl_ohp)
```




```{r}
#| label: latest-change
#| echo: false
#| results: asis
cat(rmdhelp::get_latest_change())
```


